version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /src
    command: /venv/bin/uvicorn --host 0.0.0.0 main:app --reload
    env_file:
      - rest.env
    ports:
      - "8000:8000"
  db:
    image: mongo:6.0.13-jammy
    restart: always
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
    command: ["--bind_ip_all"]
    healthcheck:
      test: ["CMD-SHELL", "mongo"]
      interval: 10s
      timeout: 5s
      retries: 5